[build]
  functions = "netlify/functions"
  publish = "."

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "GITHUB_TOKEN,ADMIN_PASSWORD,GITHUB_OWNER,GITHUB_REPO,GITHUB_BRANCH,NETLIFY_AUTH_TOKEN,NETLIFY_SITE_ID"

[functions]
  node_bundler = "esbuild"
